version: "3.3"
services:
  dummy_server:
    build: ./dummy_server_main
    container_name: dummyServer_container
    ports:
      - '12000:12000'
  
  react:
    build: ./unravel
    container_name: unravel_container
    ports:
      - "3000:3000"
    volumes:
      - ./unravel:/app
      - ./app/node_modules
    

